name: build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-22.04, pkg: gcc-9,  exe: g++-9 }
          - { os: ubuntu-22.04, pkg: gcc-10, exe: g++-10 }
          - { os: ubuntu-22.04, pkg: clang-11, exe: clang++-11 }
          - { os: ubuntu-22.04, pkg: clang-12, exe: clang++-12 }
          - { os: ubuntu-latest, pkg: gcc-11, exe: g++-11 }
          - { os: ubuntu-latest, pkg: gcc-12, exe: g++-12 }
          - { os: ubuntu-latest, pkg: clang-14, exe: clang++-14 }
          - { os: ubuntu-latest, pkg: clang-15, exe: clang++-15 }
          - { os: ubuntu-latest, pkg: clang-16, exe: clang++-16 }
          - { os: ubuntu-latest, pkg: clang-17, exe: clang++-17 }
          - { os: ubuntu-latest, pkg: clang-18, exe: clang++-18 }
        build_type: [Release, Debug]
    runs-on: ${{matrix.target.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      run: |
        echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu focal main universe" | sudo tee /etc/apt/sources.list
        sudo apt update
        sudo apt install -y software-properties-common ${{matrix.target.pkg}}

    - name: Configure CMake
      env:
        CXX: ${{matrix.target.exe}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGAIA_BUILD_UNITTEST=ON -DGAIA_BUILD_EXAMPLES=ON -DGAIA_BUILD_BENCHMARK=OFF -DGAIA_GENERATE_CC=OFF -S . -B ${{github.workspace}}/build

    - name: Build
      env:
        CXX: ${{matrix.target.exe}}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: 
      run: |
        ${{github.workspace}}/build/src/test/${{matrix.build_type}}/gaia_test

  build-linux-libcpp:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-22.04, pkg: clang-11, exe: clang++-11 }
          - { os: ubuntu-22.04, pkg: clang-12, exe: clang++-12 }
          - { os: ubuntu-latest, pkg: clang-14, exe: clang++-14 }
          - { os: ubuntu-latest, pkg: clang-15, exe: clang++-15 }
          - { os: ubuntu-latest, pkg: clang-16, exe: clang++-16 }
          - { os: ubuntu-latest, pkg: clang-17, exe: clang++-17 }
          - { os: ubuntu-latest, pkg: clang-18, exe: clang++-18 }
        build_type: [Release, Debug]
    runs-on: ${{matrix.target.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      run: |
        echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu focal main universe" | sudo tee /etc/apt/sources.list
        sudo apt update
        sudo apt install -y software-properties-common ${{matrix.target.pkg}}

    - name: Configure CMake
      env:
        CXX: ${{matrix.target.exe}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGAIA_BUILD_UNITTEST=ON -DGAIA_BUILD_EXAMPLES=ON -DGAIA_BUILD_BENCHMARK=OFF -DGAIA_GENERATE_CC=OFF -S . -B ${{github.workspace}}/build

    - name: Build
      env:
        CXX: ${{matrix.target.exe}}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: 
      run: |
        ${{github.workspace}}/build/src/test/${{matrix.build_type}}/gaia_test

  build-windows:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        toolset: [clang-cl, default, v141, v142, v143]
        include:
          - toolset: clang-cl
            toolset_option: -T"ClangCl"
          - toolset: v141
            toolset_option: -T"v141"
          - toolset: v142
            toolset_option: -T"v142"
          - toolset: v143
            toolset_option: -T"v143"
        build_type: [Release, Debug]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake ${{matrix.toolset_option}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGAIA_BUILD_UNITTEST=OFF -DGAIA_BUILD_EXAMPLES=ON -DGAIA_BUILD_BENCHMARK=OFF -DGAIA_GENERATE_CC=OFF -S . -B ${{github.workspace}}/build

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: 
      run: |
        ${{github.workspace}}/build/src/test/${{matrix.build_type}}/gaia_test.exe

  build-macos:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGAIA_BUILD_UNITTEST=ON -DGAIA_BUILD_EXAMPLES=ON -DGAIA_BUILD_BENCHMARK=OFF -DGAIA_GENERATE_CC=OFF -S . -B ${{github.workspace}}/build

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: 
      run: |
        ${{github.workspace}}/build/src/test/gaia_test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
