name: coverage

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'build.yml'
      - 'coverage.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'build.yml'
      - 'coverage.yml'
  workflow_dispatch:

jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang llvm

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-${{runner.os}}-clang-Debug
        create-symlink: true

    - name: Compile tests
      env:
        CXXFLAGS: "--coverage -fno-elide-constructors -fno-inline -fno-default-inline -fprofile-update=atomic"
        CC: ccache clang
        CXX: ccache clang++
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug \
              -DGAIA_BUILD_UNITTEST=ON \
              -DGAIA_BUILD_EXAMPLES=OFF \
              -DGAIA_BUILD_BENCHMARK=OFF \
              -DGAIA_GENERATE_CC=OFF \
              -S . -B ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --config Debug

    - name: Run tests and generate coverage data
      working-directory: ${{ github.workspace }}/build/src/test
      run: |
        LLVM_PROFILE_FILE=default.profraw ./gaia_test
        llvm-profdata merge -sparse default.profraw -o coverage.profdata
        llvm-cov export ./gaia_test \
          -instr-profile=coverage.profdata \
          -format=lcov > ${{ github.workspace }}/build/coverage.info
        llvm-cov report ./gaia_test -instr-profile=coverage.profdata

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ github.workspace }}/build/coverage.info
        name: gaia-ecs
        fail_ci_if_error: true
