name: icx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE_REL: Release
  BUILD_TYPE_DBG: Debug

jobs:
  icx:
    timeout-minutes: 10
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: |
        wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18673/l_BaseKit_p_2022.2.0.262_offline.sh
        sudo sh ./l_BaseKit_p_2022.2.0.262_offline.sh

    - name: Configure CMake
      env:
        CXX: icx
      run: |
        source /opt/intel/oneapi/setvars.sh intel64
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGAIA_BUILD_UNITTEST=ON -DGAIA_BUILD_EXAMPLES=ON -DGAIA_BUILD_BENCHMARK=OFF -DGAIA_GENERATE_CC=OFF -S . -B ${{github.workspace}}/build

    - name: Build
      env:
        CXX: icx
      run: |
        source /opt/intel/oneapi/setvars.sh intel64
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: 
      run: |
        ${{github.workspace}}/build/src/test/gaia_test
